version: "3"
services:

  mysql:
    image: mysql/mysql-server:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./scripts/db:/data/application
    environment:
      MYSQL_ROOT_PASSWORD: silver
      MYSQL_USER: silver
      MYSQL_PASSWORD: silver
      MYSQL_DATABASE: silverlabs
    ports:
      - "3306:3306"
    container_name: silver-clean-code-mysql
    network_mode: "bridge"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: silver
      POSTGRES_PASSWORD: silver
      POSTGRES_DB: silver
    ports:
      - "5432:5432"